import { useState } from "react";
import { ArrowLeft, Play, Send } from "lucide-react";
import { authorizedRequest } from "../services/authService";
import { PROGRAM_STARTERS } from "../utils/executionLanguages";
import { editCodeWithKeyboard } from "../utils/codeEditor";
import { markDailyQuestionActivity } from "../services/dailyActivity";

function CatalogPracticeWorkspace({ problem, onBack }) {
  const [language, setLanguage] = useState("JavaScript");
  const [code, setCode] = useState(PROGRAM_STARTERS.JavaScript);
  const [stdin, setStdin] = useState("");
  const [busy, setBusy] = useState("");
  const [output, setOutput] = useState(null);
  const [error, setError] = useState("");
  const changeLanguage = (next) => { setLanguage(next); setCode(PROGRAM_STARTERS[next]); setOutput(null); };
  const keyDown = (event) => { const edit=editCodeWithKeyboard(code,event.currentTarget.selectionStart,event.currentTarget.selectionEnd,event.key);if(!edit)return;event.preventDefault();setCode(edit.value);requestAnimationFrame(()=>event.currentTarget.setSelectionRange(edit.selection,edit.selection)); };
  const run = async () => { setBusy("run");setError("");setOutput(null);try{setOutput(await authorizedRequest("/api/code/custom-run",{method:"POST",timeoutMs:65000,body:JSON.stringify({code,language,stdin})}));markDailyQuestionActivity();}catch(failure){setError(failure.message);}finally{setBusy("");} };
  const submit = async () => { setBusy("submit");setError("");setOutput(null);try{const review=await authorizedRequest("/api/code/review",{method:"POST",timeoutMs:30000,body:JSON.stringify({code,language,problem:`${problem.title}: ${problem.description}`})});setOutput({review});markDailyQuestionActivity();}catch(failure){setError(failure.message);}finally{setBusy("");} };
  return <div className="space-y-5"><button type="button" onClick={onBack} className="flex items-center gap-2 text-sm font-bold text-violet-600"><ArrowLeft size={16}/> Back to catalog</button><section className="surface-card rounded-3xl p-6"><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold capitalize text-violet-700">{problem.difficulty}</span><h1 className="mt-4 text-2xl font-black">{problem.title}</h1><p className="mt-2 text-sm font-bold text-violet-600">{problem.topic}</p><p className="mt-4 leading-7 text-gray-600 dark:text-gray-300">{problem.description}</p><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-gray-500">{problem.constraints.map((item)=><li key={item}>{item}</li>)}</ul></section><section className="surface-card overflow-hidden rounded-3xl"><div className="flex items-center justify-between border-b border-gray-200 p-4 dark:border-gray-800"><h2 className="font-extrabold">Solution</h2><select value={language} onChange={(event)=>changeLanguage(event.target.value)} className="rounded-xl border bg-transparent px-3 py-2 dark:border-gray-700">{Object.keys(PROGRAM_STARTERS).map((item)=><option key={item}>{item}</option>)}</select></div><textarea aria-label="Catalog solution code" spellCheck={false} value={code} onKeyDown={keyDown} onChange={(event)=>setCode(event.target.value)} className="min-h-[360px] w-full resize-y bg-slate-950 p-5 font-mono text-sm leading-6 text-slate-100 outline-none"/><div className="grid gap-4 border-t border-gray-200 p-5 dark:border-gray-800 sm:grid-cols-2"><label className="text-sm font-bold">Custom input<textarea value={stdin} onChange={(event)=>setStdin(event.target.value)} rows={5} className="mt-2 w-full rounded-xl border bg-transparent p-3 font-mono font-normal dark:border-gray-700"/></label><div><p className="text-sm font-bold">Program output</p><pre className="mt-2 min-h-28 whitespace-pre-wrap rounded-xl bg-gray-950 p-3 text-xs text-gray-100">{output?.stdout||output?.stderr||output?.compilation||output?.review?.summary||"Run your program to see output."}</pre></div></div><div className="flex flex-wrap gap-3 border-t border-gray-200 p-5 dark:border-gray-800"><button disabled={Boolean(busy)||!code.trim()} onClick={run} className="flex items-center gap-2 rounded-xl border px-5 py-3 font-bold disabled:opacity-40"><Play size={17}/>{busy==="run"?"Running...":"Run code"}</button><button disabled={Boolean(busy)||!code.trim()} onClick={submit} className="flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white disabled:opacity-40"><Send size={17}/>{busy==="submit"?"Reviewing...":"Submit for review"}</button></div>{error&&<p role="alert" className="px-5 pb-5 text-sm font-semibold text-rose-600">{error}</p>}</section></div>;
}

export default CatalogPracticeWorkspace;
