import CodeAssessmentWorkspace from "../components/CodeAssessmentWorkspace";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, Circle, Code2, FlaskConical, Lightbulb, LoaderCircle, Play, RotateCcw, Send, Sparkles, TerminalSquare } from "lucide-react";
import { codingProblems } from "../data/codingProblems";
import { addHistoryEntry } from "../services/history";
import { useAuth } from "../context/AuthContext";
import { getAccountStorageKey, readStorage, writeStorage } from "../utils/storage";
import { normalizeCodeDrafts, validateCodeTokens } from "../utils/codeValidation";
import { CODING_LANGUAGES, getStarterCode, getValidationTokens } from "../utils/codingLanguages";
import { generateQuestionBatch, reviewCodingSolution } from "../services/questionService";
import { getCodingCatalogBatch, needsCodingDifficultyBatch, normalizeCodingWorkspaceState } from "../utils/codingWorkspaceState";
import CareerRoadmap from "../components/CareerRoadmap";

const difficultyStyle = { Easy: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300", Medium: "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300", Hard: "bg-rose-50 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300" };
const defaultDrafts = Object.fromEntries(codingProblems.flatMap((item)=>Object.entries(item.templates).map(([language,code])=>[`${item.id}:${language}`,code])));
const CODING_DRAFTS_KEY = "prepmentor_coding_drafts";
const CODING_WORKSPACE_KEY = "prepmentor_coding_workspace";

function CodingWorkspace() {
  const { user } = useAuth();
  const storageKey = getAccountStorageKey(CODING_DRAFTS_KEY, user);
  const workspaceStorageKey = getAccountStorageKey(CODING_WORKSPACE_KEY, user);
  const [initialWorkspace] = useState(() => normalizeCodingWorkspaceState(readStorage(workspaceStorageKey, null), codingProblems));
  const [problems,setProblems]=useState(initialWorkspace.problems); const [problemId,setProblemId]=useState(initialWorkspace.problemId); const [language,setLanguage]=useState(initialWorkspace.language); const [filter,setFilter]=useState(initialWorkspace.filter);
  const [catalogOffset,setCatalogOffset]=useState(initialWorkspace.catalogOffset); const [catalogSource,setCatalogSource]=useState(initialWorkspace.catalogSource); const [generating,setGenerating]=useState(false); const [generationError,setGenerationError]=useState("");
  const problem=problems.find((item)=>item.id===problemId) || problems[0];
  const [drafts,setDrafts]=useState(()=>normalizeCodeDrafts(readStorage(storageKey, null), defaultDrafts));
  const [feedback,setFeedback]=useState(null); const [submitted,setSubmitted]=useState(false); const [hint,setHint]=useState(initialWorkspace.hint); const [reviewing,setReviewing]=useState(false);
  const key=`${problem.id}:${language}`; const code=drafts[key] ?? problem.templates?.[language] ?? getStarterCode(language,problem.title);
  const visible=useMemo(()=>problems.filter((item)=>filter==="All"||item.difficulty===filter),[filter,problems]);
  const submissionScore=useMemo(()=>{if(!submitted||!feedback?.length)return null;const reviewed=String(feedback[0]?.name||"").match(/(\d+)%/);return reviewed?Number(reviewed[1]):Math.round((feedback.filter((item)=>item.passed).length/feedback.length)*100);},[feedback,submitted]);
  const selectProblem=(id)=>{setProblemId(id);setFeedback(null);setSubmitted(false);setHint(0);};
  useEffect(()=>{const timer=window.setTimeout(()=>writeStorage(storageKey,drafts),500);return()=>window.clearTimeout(timer);},[drafts,storageKey]);
  useEffect(()=>{const timer=window.setTimeout(()=>writeStorage(workspaceStorageKey,{problems,problemId,language,filter,catalogOffset,catalogSource,hint}),500);return()=>window.clearTimeout(timer);},[catalogOffset,catalogSource,filter,hint,language,problemId,problems,workspaceStorageKey]);
  const validate=()=>{const checks=validateCodeTokens(code,language,problem.tokens?.[language] || getValidationTokens());setFeedback(checks);setSubmitted(false);return checks;};
  const submit=async()=>{if(reviewing)return;const checks=feedback || validate();let score=Math.round((checks.filter((item)=>item.passed).length/checks.length)*100);setReviewing(true);setSubmitted(false);try{const review=await reviewCodingSolution({code,language,problem:`${problem.title}\n${problem.description}\nConstraints: ${problem.constraints.join("; ")}`});score=review.score;setFeedback([{name:`AI semantic review · ${score}%`,passed:score>=70,detail:`${review.summary} Complexity: ${review.complexity}${review.issues.length?` Issues: ${review.issues.join("; ")}`:""}`},...checks]);}catch{setFeedback(checks);}finally{addHistoryEntry({title:`Coding Lab · ${problem.title}`,type:"Coding Practice",evidenceType:"semantic-or-static-review",score,duration:"Self-paced"});setSubmitted(true);setReviewing(false);}};
  const reset=()=>{setDrafts((current)=>({...current,[key]:problem.templates?.[language] ?? getStarterCode(language,problem.title)}));setFeedback(null);setSubmitted(false);};
  const generateProblems=async(requestedOffset,requestedDifficulty=filter)=>{setGenerating(true);setGenerationError("");try{const batch=getCodingCatalogBatch(catalogOffset,requestedOffset);const response=await generateQuestionBatch({kind:"coding",count:batch.count,difficulty:requestedDifficulty==="All"?"medium":requestedDifficulty.toLowerCase(),language,offset:batch.offset});const generated=response.questions.map((item)=>({...item,title:item.title||item.question,difficulty:item.difficulty[0].toUpperCase()+item.difficulty.slice(1),description:item.description||item.question,constraints:item.constraints||[],example:item.example||"Explain your approach with an example.",hints:item.hints||[],templates:{},tokens:{}}));setProblems(generated);setProblemId(generated[0].id);setCatalogOffset(batch.offset);setCatalogSource(response.source||"catalog-fallback");setFeedback(null);}catch(error){setGenerationError(error.message||"Unable to generate coding questions.");}finally{setGenerating(false);}};
  const changeFilter=(level)=>{setFilter(level);if(needsCodingDifficultyBatch(problems,level)){generateProblems(catalogOffset < 0 ? 0 : catalogOffset,level);}};

  return <div className="space-y-6"><CodeAssessmentWorkspace mode="practice"/><header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-sm font-bold text-indigo-600 dark:text-indigo-400">Coding lab · 1,000-problem catalog</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight sm:text-4xl">Practice the thinking behind the code.</h1><p className="mt-2 text-gray-500 dark:text-gray-400">Use JavaScript, TypeScript, Python, Java, C++, C, C#, or Go. Generate each new batch from a different catalog position.</p><p className="mt-2 text-xs font-bold text-teal-600 dark:text-teal-400">Current source: {catalogSource === "llm" ? "fresh LLM batch" : catalogSource === "catalog-fallback" ? "offline interview catalog" : "starter collection"}</p>{generationError&&<p role="alert" className="mt-2 text-sm font-semibold text-rose-600">{generationError}</p>}</div><div className="flex flex-col gap-2 sm:flex-row"><label className="text-xs font-bold text-gray-500"><span className="mb-1 block">Jump to catalog batch</span><select value={Math.max(0,catalogOffset)} disabled={generating} onChange={(event)=>generateProblems(Number(event.target.value))} className="w-full rounded-xl border border-gray-200 bg-white px-3 py-3 text-sm font-bold text-gray-700 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200">{Array.from({length:34},(_,index)=>{const start=index*30;return <option key={start} value={start}>Problems {start+1}–{Math.min(1000,start+30)}</option>;})}</select></label><button type="button" disabled={generating} onClick={()=>generateProblems()} className="mt-auto flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{generating?<LoaderCircle className="animate-spin" size={17}/>:<Sparkles size={17}/>} {generating?"Generating…":"Next batch"}</button></div></header>
    <div className="grid items-start gap-6 xl:grid-cols-[300px_minmax(0,1fr)]"><aside className="surface-card rounded-3xl p-4"><div className="flex gap-2 overflow-x-auto pb-3">{["All","Easy","Medium","Hard"].map((level)=><button key={level} type="button" disabled={generating} onClick={()=>changeFilter(level)} className={`rounded-lg px-3 py-1.5 text-xs font-bold disabled:opacity-50 ${filter===level?"bg-indigo-600 text-white":"bg-gray-100 text-gray-500 dark:bg-gray-800"}`}>{level}</button>)}</div><div className="space-y-2">{visible.map((item)=><button key={item.id} type="button" onClick={()=>selectProblem(item.id)} className={`w-full rounded-2xl border p-4 text-left transition ${problem.id===item.id?"border-indigo-400 bg-indigo-50/70 dark:bg-indigo-950/35":"border-transparent hover:bg-gray-50 dark:hover:bg-gray-800/50"}`}><div className="flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${difficultyStyle[item.difficulty]}`}>{item.difficulty}</span><ChevronRight size={15} className="text-gray-300"/></div><p className="mt-3 text-sm font-bold">{item.title}</p><p className="mt-1 text-xs text-gray-400">{item.topic}</p></button>)}</div></aside>
      <main className="space-y-6"><section className="surface-card rounded-3xl p-6 sm:p-8"><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-black ${difficultyStyle[problem.difficulty]}`}>{problem.difficulty}</span><span className="text-xs font-bold text-gray-400">{problem.topic}</span></div><h2 className="mt-4 text-2xl font-extrabold">{problem.title}</h2><p className="mt-3 leading-7 text-gray-600 dark:text-gray-300">{problem.description}</p><div className="mt-6 grid gap-5 lg:grid-cols-2"><div><h3 className="text-xs font-black uppercase tracking-[0.16em] text-gray-400">Example</h3><pre className="mt-3 overflow-x-auto whitespace-pre-wrap rounded-2xl bg-gray-950 p-4 text-sm leading-6 text-gray-200">{problem.example}</pre></div><div><h3 className="text-xs font-black uppercase tracking-[0.16em] text-gray-400">Constraints</h3><ul className="mt-3 space-y-2 text-sm text-gray-500 dark:text-gray-400">{problem.constraints.map((item)=><li key={item} className="flex gap-2"><Circle size={7} className="mt-1.5 shrink-0 fill-current"/>{item}</li>)}</ul></div></div><button type="button" onClick={()=>setHint((value)=>Math.min(value+1,problem.hints.length))} disabled={hint===problem.hints.length} className="mt-6 flex items-center gap-2 text-sm font-bold text-amber-600 disabled:text-gray-400"><Lightbulb size={17}/> {hint===problem.hints.length?"All hints revealed":"Reveal a hint"}</button>{hint>0&&<div className="mt-3 space-y-2">{problem.hints.slice(0,hint).map((item,index)=><p key={item} className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800 dark:bg-amber-950/30 dark:text-amber-300">Hint {index+1}: {item}</p>)}</div>}</section>
        <section className="overflow-hidden rounded-3xl border border-gray-800 bg-[#0c111b] shadow-2xl shadow-gray-950/20"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-800 px-5 py-3"><span className="flex items-center gap-2 text-xs font-bold text-gray-400"><TerminalSquare size={16}/> solution</span><div className="flex items-center gap-2"><select value={language} onChange={(event)=>{setLanguage(event.target.value);setFeedback(null);setSubmitted(false);}} className="rounded-lg border border-gray-700 bg-gray-900 px-3 py-2 text-xs font-bold text-gray-200">{CODING_LANGUAGES.map((item)=><option key={item}>{item}</option>)}</select><button type="button" onClick={reset} className="rounded-lg p-2 text-gray-400 hover:bg-gray-800" aria-label="Reset starter code"><RotateCcw size={16}/></button></div></div><textarea value={code} onChange={(event)=>{setDrafts((current)=>({...current,[key]:event.target.value}));setFeedback(null);setSubmitted(false);}} spellCheck="false" aria-label="Code editor" className="min-h-[360px] w-full resize-y bg-transparent p-5 font-mono text-sm leading-7 text-gray-100 outline-none"/><div className="border-t border-gray-800 bg-[#101622] p-4"><div className="flex flex-wrap justify-end gap-3"><button type="button" onClick={validate} className="flex items-center gap-2 rounded-xl border border-gray-700 px-4 py-2.5 text-sm font-bold text-gray-200 hover:bg-gray-800"><Play size={16}/> Run static checks</button><button type="button" onClick={submit} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-indigo-500"><Send size={16}/> Submit attempt</button></div></div></section>
        {feedback&&<section className="surface-card rounded-3xl p-6"><h2 className="flex items-center gap-2 font-bold"><FlaskConical size={19} className="text-indigo-500"/> Validation feedback</h2><p className="mt-2 text-xs leading-5 text-gray-400">These checks inspect code structure only. Your code was not executed.</p><div className="mt-5 space-y-3">{feedback.map((item)=><div key={item.name} className="flex items-start gap-3 rounded-2xl border border-gray-200 p-4 dark:border-gray-700">{item.passed?<CheckCircle2 size={20} className="shrink-0 text-emerald-500"/>:<Code2 size={20} className="shrink-0 text-amber-500"/>}<div><p className="text-sm font-bold">{item.name}</p><p className="mt-1 text-xs text-gray-500">{item.passed?"Detected in your draft.":`${item.detail} was not found. Review the hint and implementation.`}</p></div></div>)}</div>{submitted&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">Attempt saved to your preparation history.</p>}</section>}{submissionScore!==null&&<CareerRoadmap score={submissionScore} module="Coding practice" topicPerformance={[{topic:problem.topic,percentage:submissionScore}]}/>}</main></div></div>;
}

export default CodingWorkspace;
