import { useState } from "react";
import { CheckCircle2, Code2, Play, Send, TerminalSquare } from "lucide-react";

const starter = `function twoSum(numbers, target) {\n  // Return the indices of two numbers that add up to target.\n  \n}`;

function CodingInterview() {
  const [code, setCode] = useState(starter);
  const [language, setLanguage] = useState("JavaScript");
  const [output, setOutput] = useState("Run your code to see mock test feedback.");
  const [submitted, setSubmitted] = useState(false);
  const run = () => setOutput(code.includes("return") ? "2 / 3 sample tests passed. Hidden tests are not executed in mock mode." : "0 / 3 sample tests passed. Add a return statement to your solution.");

  return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-bold text-indigo-600 dark:text-indigo-400">Coding lab · Mock execution</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">Two Sum</h1><p className="mt-2 text-gray-500 dark:text-gray-400">Practice explaining and refining a solution in an interview-style workspace.</p></div><select value={language} onChange={(e)=>setLanguage(e.target.value)} className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm font-semibold dark:border-gray-700 dark:bg-gray-900"><option>JavaScript</option><option>Python</option><option>Java</option></select></header>
    <div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><section className="surface-card rounded-3xl p-6"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950"><Code2 size={22}/></div><h2 className="text-xl font-bold">Problem description</h2><p className="mt-3 leading-7 text-gray-600 dark:text-gray-300">Given an array of integers and a target, return the indices of the two values whose sum equals the target. You may assume exactly one valid answer exists.</p><h3 className="mt-6 text-sm font-bold uppercase tracking-wider text-gray-400">Example</h3><pre className="mt-3 overflow-x-auto rounded-2xl bg-gray-950 p-4 text-sm leading-6 text-gray-200">Input: [2, 7, 11, 15], 9{`\n`}Output: [0, 1]</pre><h3 className="mt-6 font-bold">Constraints</h3><ul className="mt-2 list-inside list-disc space-y-2 text-sm text-gray-500"><li>2 ≤ numbers.length ≤ 10,000</li><li>Return indices, not values</li><li>Avoid using the same element twice</li></ul></section>
    <section className="overflow-hidden rounded-3xl border border-gray-800 bg-[#0d111b] shadow-2xl shadow-gray-950/20"><div className="flex items-center justify-between border-b border-gray-800 px-5 py-3 text-xs font-bold text-gray-400"><span className="flex items-center gap-2"><TerminalSquare size={16}/> solution.{language === "Python" ? "py" : language === "Java" ? "java" : "js"}</span><span>Mock runner</span></div><textarea value={code} onChange={(e)=>setCode(e.target.value)} spellCheck="false" aria-label="Code editor" className="min-h-[360px] w-full resize-y bg-transparent p-5 font-mono text-sm leading-7 text-gray-100 outline-none"/><div className="border-t border-gray-800 bg-[#101622] p-4"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-gray-500">Console</p><p className="min-h-10 text-sm text-gray-300">{output}</p><div className="mt-4 flex flex-wrap justify-end gap-3"><button onClick={run} className="flex items-center gap-2 rounded-xl border border-gray-700 px-4 py-2.5 text-sm font-bold text-gray-200 hover:bg-gray-800"><Play size={16}/> Run samples</button><button onClick={()=>setSubmitted(true)} className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-indigo-500"><Send size={16}/> Submit solution</button></div>{submitted&&<p className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-950/50 p-3 text-sm text-emerald-300"><CheckCircle2 size={17}/> Solution saved as a practice attempt. No remote code was executed.</p>}</div></section></div>
  </div>;
}

export default CodingInterview;
